<?php

namespace Database\Seeders;

use App\Models\PosHunterSentence;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PosHunterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sentences = [
            ['difficulty' => 'easy', 'sentence' => 'The dog barked loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'She drank water.'],
            ['difficulty' => 'easy', 'sentence' => 'He reads books daily.'],
            ['difficulty' => 'easy', 'sentence' => 'Birds fly high.'],
            ['difficulty' => 'easy', 'sentence' => 'The sun shines brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'They play soccer.'],
            ['difficulty' => 'easy', 'sentence' => 'She likes flowers.'],
            ['difficulty' => 'easy', 'sentence' => 'The baby sleeps quietly.'],
            ['difficulty' => 'easy', 'sentence' => 'He eats apples.'],
            ['difficulty' => 'easy', 'sentence' => 'Fish swim in water.'],
            ['difficulty' => 'easy', 'sentence' => 'She sings beautifully.'],
            ['difficulty' => 'easy', 'sentence' => 'The wind blows softly.'],
            ['difficulty' => 'easy', 'sentence' => 'They watch movies.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat sleeps often.'],
            ['difficulty' => 'easy', 'sentence' => 'She reads stories.'],
            ['difficulty' => 'easy', 'sentence' => 'The sky is blue.'],
            ['difficulty' => 'easy', 'sentence' => 'He walks daily.'],
            ['difficulty' => 'easy', 'sentence' => 'The trees are tall.'],
            ['difficulty' => 'easy', 'sentence' => 'They ride bikes.'],
            ['difficulty' => 'easy', 'sentence' => 'He plays guitar.'],
            ['difficulty' => 'easy', 'sentence' => 'She swims fast.'],
            ['difficulty' => 'easy', 'sentence' => 'The leaves are green.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog wags its tail.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws pictures.'],
            ['difficulty' => 'easy', 'sentence' => 'The car is red.'],
            ['difficulty' => 'easy', 'sentence' => 'They jump high.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat purrs softly.'],
            ['difficulty' => 'easy', 'sentence' => 'He runs fast.'],
            ['difficulty' => 'easy', 'sentence' => 'She paints well.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The cake smells good.'],
            ['difficulty' => 'easy', 'sentence' => 'She skips happily.'],
            ['difficulty' => 'easy', 'sentence' => 'He listens carefully.'],
            ['difficulty' => 'easy', 'sentence' => 'The grass is green.'],
            ['difficulty' => 'easy', 'sentence' => 'They clap loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The child smiles brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'She dances gracefully.'],
            ['difficulty' => 'easy', 'sentence' => 'The door is open.'],
            ['difficulty' => 'easy', 'sentence' => 'They eat together.'],
            ['difficulty' => 'easy', 'sentence' => 'He laughs often.'],
            ['difficulty' => 'easy', 'sentence' => 'The book is old.'],
            ['difficulty' => 'easy', 'sentence' => 'She cooks dinner.'],
            ['difficulty' => 'easy', 'sentence' => 'The table is clean.'],
            ['difficulty' => 'easy', 'sentence' => 'They drive slowly.'],
            ['difficulty' => 'easy', 'sentence' => 'The bird sings sweetly.'],
            ['difficulty' => 'easy', 'sentence' => 'He talks calmly.'],
            ['difficulty' => 'easy', 'sentence' => 'She walks quickly.'],
            ['difficulty' => 'easy', 'sentence' => 'The fish are small.'],
            ['difficulty' => 'easy', 'sentence' => 'They dance together.'],
            ['difficulty' => 'easy', 'sentence' => 'He writes neatly.'],
            ['difficulty' => 'easy', 'sentence' => 'The house is big.'],
            ['difficulty' => 'easy', 'sentence' => 'She knits scarves.'],
            ['difficulty' => 'easy', 'sentence' => 'They talk softly.'],
            ['difficulty' => 'easy', 'sentence' => 'The chair is broken.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws flowers.'],
            ['difficulty' => 'easy', 'sentence' => 'The apple is red.'],
            ['difficulty' => 'easy', 'sentence' => 'They hike often.'],
            ['difficulty' => 'easy', 'sentence' => 'He works hard.'],
            ['difficulty' => 'easy', 'sentence' => 'The boy is tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She whispers softly.'],
            ['difficulty' => 'easy', 'sentence' => 'The cake is sweet.'],
            ['difficulty' => 'easy', 'sentence' => 'He listens quietly.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh together.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat is soft.'],
            ['difficulty' => 'easy', 'sentence' => 'She bakes cookies.'],
            ['difficulty' => 'easy', 'sentence' => 'The dog is playful.'],
            ['difficulty' => 'easy', 'sentence' => 'They swim together.'],
            ['difficulty' => 'easy', 'sentence' => 'He cleans the car.'],
            ['difficulty' => 'easy', 'sentence' => 'The lamp is bright.'],
            ['difficulty' => 'easy', 'sentence' => 'She reads books.'],
            ['difficulty' => 'easy', 'sentence' => 'The soup is hot.'],
            ['difficulty' => 'easy', 'sentence' => 'He sings songs.'],
            ['difficulty' => 'easy', 'sentence' => 'The plant grows tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She writes stories.'],
            ['difficulty' => 'easy', 'sentence' => 'The car is fast.'],
            ['difficulty' => 'easy', 'sentence' => 'They walk slowly.'],
            ['difficulty' => 'easy', 'sentence' => 'The flower smells nice.'],
            ['difficulty' => 'easy', 'sentence' => 'She knits blankets.'],
            ['difficulty' => 'easy', 'sentence' => 'The floor is clean.'],
            ['difficulty' => 'easy', 'sentence' => 'They laugh loudly.'],
            ['difficulty' => 'easy', 'sentence' => 'The room is dark.'],
            ['difficulty' => 'easy', 'sentence' => 'She dances well.'],
            ['difficulty' => 'easy', 'sentence' => 'He drinks milk.'],
            ['difficulty' => 'easy', 'sentence' => 'The tree is tall.'],
            ['difficulty' => 'easy', 'sentence' => 'She smiles brightly.'],
            ['difficulty' => 'easy', 'sentence' => 'The baby is asleep.'],
            ['difficulty' => 'easy', 'sentence' => 'He runs quickly.'],
            ['difficulty' => 'easy', 'sentence' => 'The boat floats.'],
            ['difficulty' => 'easy', 'sentence' => 'She draws animals.'],
            ['difficulty' => 'easy', 'sentence' => 'The snow is white.'],
            ['difficulty' => 'easy', 'sentence' => 'He likes movies.'],
            ['difficulty' => 'easy', 'sentence' => 'The cheese is tasty.'],
            ['difficulty' => 'easy', 'sentence' => 'She enjoys music.'],
            ['difficulty' => 'easy', 'sentence' => 'They eat pizza.'],
            ['difficulty' => 'easy', 'sentence' => 'The fire burns bright.'],
            ['difficulty' => 'easy', 'sentence' => 'He climbs trees.'],
            ['difficulty' => 'easy', 'sentence' => 'The sky is clear.'],
            ['difficulty' => 'easy', 'sentence' => 'She drives fast.'],
            ['difficulty' => 'easy', 'sentence' => 'The milk is cold.'],
            ['difficulty' => 'easy', 'sentence' => 'They watch sports.'],
            ['difficulty' => 'easy', 'sentence' => 'He draws cars.'],
            ['difficulty' => 'easy', 'sentence' => 'The cat is fluffy.'],
            ['difficulty' => 'mid', 'sentence' => 'The quick brown fox jumps over the lazy dog.'],
            ['difficulty' => 'mid', 'sentence' => 'She sells seashells by the seashore.'],
            ['difficulty' => 'mid', 'sentence' => 'Peter Piper picked a peck of pickled peppers.'],
            ['difficulty' => 'mid', 'sentence' => 'A big black bear sat on a big black rug.'],
            ['difficulty' => 'mid', 'sentence' => 'She swiftly swam across the sparkling sea.'],
            ['difficulty' => 'mid', 'sentence' => 'The early bird catches the worm every morning.'],
            ['difficulty' => 'mid', 'sentence' => 'He quickly packed his bags and left for the airport.'],
            ['difficulty' => 'mid', 'sentence' => 'The children played happily in the sunny park.'],
            ['difficulty' => 'mid', 'sentence' => 'She carefully painted the beautiful landscape.'],
            ['difficulty' => 'mid', 'sentence' => 'The chef prepared a delicious meal for the guests.'],
            ['difficulty' => 'mid', 'sentence' => 'They eagerly awaited the arrival of their friends.'],
            ['difficulty' => 'mid', 'sentence' => 'The teacher explained the complex problem clearly.'],
            ['difficulty' => 'mid', 'sentence' => 'He diligently worked on his project all night.'],
            ['difficulty' => 'mid', 'sentence' => 'The musician played the piano with great skill.'],
            ['difficulty' => 'mid', 'sentence' => 'She gracefully danced across the stage.'],
            ['difficulty' => 'mid', 'sentence' => 'The scientist conducted the experiment with precision.'],
            ['difficulty' => 'mid', 'sentence' => 'They explored the dense forest with excitement.'],
            ['difficulty' => 'mid', 'sentence' => 'The artist sketched a portrait of the old man.'],
            ['difficulty' => 'mid', 'sentence' => 'He read the lengthy novel in just a few days.'],
            ['difficulty' => 'hard', 'sentence' => 'How much wood would a woodchuck chuck if a woodchuck could chuck wood?'],
            ['difficulty' => 'hard', 'sentence' => 'The intricacies of quantum mechanics baffle even the most brilliant minds.'],
            ['difficulty' => 'hard', 'sentence' => 'She meticulously crafted a detailed replica of the ancient artifact.'],
            ['difficulty' => 'hard', 'sentence' => 'The expedition team navigated through the treacherous terrain with caution.'],
            ['difficulty' => 'hard', 'sentence' => 'He eloquently articulated his thoughts during the intense debate.'],
            ['difficulty' => 'hard', 'sentence' => 'The symphony orchestra performed a complex and captivating piece.'],
            ['difficulty' => 'hard', 'sentence' => 'She deciphered the cryptic message hidden within the ancient manuscript.'],
            ['difficulty' => 'hard', 'sentence' => 'The architect designed an innovative and sustainable skyscraper.'],
            ['difficulty' => 'hard', 'sentence' => 'He conducted a thorough analysis of the financial market trends.'],
            ['difficulty' => 'hard', 'sentence' => 'The biologist discovered a new species in the remote rainforest.'],
            ['difficulty' => 'hard', 'sentence' => 'She composed a symphony that was both intricate and harmonious.'],
            ['difficulty' => 'hard', 'sentence' => 'The historian uncovered a wealth of information about the lost civilization.'],
            ['difficulty' => 'hard', 'sentence' => 'He developed a groundbreaking algorithm for data encryption.'],
            ['difficulty' => 'hard', 'sentence' => 'The novelist wrote a compelling and multifaceted narrative.'],
            ['difficulty' => 'hard', 'sentence' => 'She performed a delicate and precise surgical procedure.'],
            ['difficulty' => 'hard', 'sentence' => 'The engineer designed a highly efficient and innovative machine.'],
            ['difficulty' => 'hard', 'sentence' => 'He presented a comprehensive and well-researched thesis.'],
            ['difficulty' => 'hard', 'sentence' => 'The linguist translated the ancient text with remarkable accuracy.'],
            ['difficulty' => 'hard', 'sentence' => 'She choreographed a complex and visually stunning dance routine.'],
            ['difficulty' => 'hard', 'sentence' => 'The mathematician solved a notoriously difficult problem.'],
            ['difficulty' => 'hard', 'sentence' => 'He navigated the intricate legal system with expertise.'],
            ['difficulty' => 'hard', 'sentence' => 'The astrophysicist formulated a hypothesis about the origins of the universe.'],
            ['difficulty' => 'hard', 'sentence' => 'She synthesized a new compound with potential pharmaceutical applications.'],
            ['difficulty' => 'hard', 'sentence' => 'The philosopher pondered the existential questions of human existence.'],
            ['difficulty' => 'hard', 'sentence' => 'He orchestrated a complex merger between two multinational corporations.'],
            ['difficulty' => 'hard', 'sentence' => 'The poet composed a sonnet with intricate and evocative imagery.'],
            ['difficulty' => 'hard', 'sentence' => 'She engineered a solution to a previously unsolvable problem.'],
            ['difficulty' => 'hard', 'sentence' => 'The economist developed a model to predict future market fluctuations.'],
            ['difficulty' => 'hard', 'sentence' => 'He conducted an exhaustive study on the effects of climate change.'],
            ['difficulty' => 'hard', 'sentence' => 'The surgeon performed a groundbreaking and highly complex operation.'],
            ['difficulty' => 'hard', 'sentence' => 'She analyzed the sociopolitical implications of the new policy.'],
            ['difficulty' => 'hard', 'sentence' => 'The linguist deciphered an ancient and nearly forgotten language.'],
            ['difficulty' => 'hard', 'sentence' => 'He composed a symphony that challenged traditional musical conventions.'],
            ['difficulty' => 'hard', 'sentence' => 'The architect designed a building that defied conventional aesthetics.'],
            ['difficulty' => 'hard', 'sentence' => 'She conducted a meta-analysis of numerous scientific studies.'],
            ['difficulty' => 'hard', 'sentence' => 'The historian provided a nuanced interpretation of historical events.'],
            ['difficulty' => 'hard', 'sentence' => 'He developed a theoretical framework for understanding complex systems.'],
            ['difficulty' => 'hard', 'sentence' => 'The biochemist discovered a novel pathway in cellular metabolism.'],
            ['difficulty' => 'hard', 'sentence' => 'She wrote a dissertation on the philosophical underpinnings of ethics.'],
            ['difficulty' => 'hard', 'sentence' => 'The engineer created a prototype of a revolutionary new device.']
        ];
        foreach ($sentences as $sentence) {
            PosHunterSentence::create($sentence);
        }
    }
}
